version: "3"

services:
  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    restart: always
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: mysecretpassword
      DB_NAME: postgres
      DB_SSL_MODE: require
      JWT_SECRET: secret
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:4003
    ports:
      - "4000:4000"  # Expose Go app port